apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: {{ .Values.apiSecretName }}
            namespace: kube-system
            key: apiKey
      serviceUrl: >-
        {{ .Values.serviceURL }}
